--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.applications (
    application_id bigint NOT NULL,
    applicant_id bigint NOT NULL,
    applied_at timestamp(6) without time zone,
    job_id bigint NOT NULL,
    resume_id bigint NOT NULL,
    status character varying(30) NOT NULL
);


--
-- Name: applications_application_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.applications ALTER COLUMN application_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.applications_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: educations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.educations (
    education_id bigint NOT NULL,
    degree character varying(200),
    end_year integer,
    field_of_study character varying(255),
    grade character varying(50),
    institution character varying(255),
    resume_id bigint NOT NULL,
    start_year integer
);


--
-- Name: educations_education_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.educations ALTER COLUMN education_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.educations_education_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experiences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experiences (
    experience_id bigint NOT NULL,
    company character varying(255),
    description text,
    end_date date,
    job_title character varying(200),
    resume_id bigint NOT NULL,
    start_date date
);


--
-- Name: experiences_experience_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.experiences ALTER COLUMN experience_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiences_experience_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_embeddings (
    embedding_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    embedding public.vector(384),
    job_id bigint NOT NULL
);


--
-- Name: job_embeddings_embedding_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.job_embeddings ALTER COLUMN embedding_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_embeddings_embedding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    job_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text NOT NULL,
    education_requirement text,
    location character varying(200),
    minimum_experience numeric(4,1),
    recruiter_id bigint NOT NULL,
    required_skills text,
    title character varying(200) NOT NULL
);


--
-- Name: jobs_job_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.jobs ALTER COLUMN job_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    token_id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: password_reset_tokens_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN token_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resume_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resume_embeddings (
    embedding_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    embedding public.vector(384),
    resume_id bigint NOT NULL
);


--
-- Name: resume_embeddings_embedding_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resume_embeddings ALTER COLUMN embedding_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_embeddings_embedding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resume_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resume_skills (
    resume_id bigint NOT NULL,
    skill_id bigint NOT NULL
);


--
-- Name: resumes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resumes (
    resume_id bigint NOT NULL,
    applicant_id bigint NOT NULL,
    extracted_text text,
    file_name character varying(255) NOT NULL,
    file_path text NOT NULL,
    file_type character varying(50),
    uploaded_at timestamp(6) without time zone
);


--
-- Name: resumes_resume_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resumes ALTER COLUMN resume_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resumes_resume_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: screening_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.screening_results (
    result_id bigint NOT NULL,
    application_id bigint NOT NULL,
    education_score numeric(5,2),
    experience_score numeric(5,2),
    final_score numeric(5,2),
    processed_at timestamp(6) without time zone,
    recommendation character varying(30),
    similarity_score numeric(5,2),
    skills_score numeric(5,2)
);


--
-- Name: screening_results_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.screening_results ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screening_results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skills (
    skill_id bigint NOT NULL,
    skill_name character varying(100) NOT NULL
);


--
-- Name: skills_skill_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.skills ALTER COLUMN skill_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skills_skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    name character varying(150) NOT NULL,
    password_hash text NOT NULL,
    role character varying(20) NOT NULL
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (application_id);


--
-- Name: educations educations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.educations
    ADD CONSTRAINT educations_pkey PRIMARY KEY (education_id);


--
-- Name: experiences experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiences
    ADD CONSTRAINT experiences_pkey PRIMARY KEY (experience_id);


--
-- Name: job_embeddings job_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_embeddings
    ADD CONSTRAINT job_embeddings_pkey PRIMARY KEY (embedding_id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (job_id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (token_id);


--
-- Name: resume_embeddings resume_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_embeddings
    ADD CONSTRAINT resume_embeddings_pkey PRIMARY KEY (embedding_id);


--
-- Name: resume_skills resume_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_skills
    ADD CONSTRAINT resume_skills_pkey PRIMARY KEY (resume_id, skill_id);


--
-- Name: resumes resumes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT resumes_pkey PRIMARY KEY (resume_id);


--
-- Name: screening_results screening_results_application_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screening_results
    ADD CONSTRAINT screening_results_application_id_key UNIQUE (application_id);


--
-- Name: screening_results screening_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screening_results
    ADD CONSTRAINT screening_results_pkey PRIMARY KEY (result_id);


--
-- Name: skills skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (skill_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: resume_embeddings uk76v9jm0era4p0p2c6oay8nvtd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_embeddings
    ADD CONSTRAINT uk76v9jm0era4p0p2c6oay8nvtd UNIQUE (resume_id);


--
-- Name: job_embeddings ukommnyepba057209o9k2fq51me; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_embeddings
    ADD CONSTRAINT ukommnyepba057209o9k2fq51me UNIQUE (job_id);


--
-- Name: skills ukqdkr64bxreqdbn6b4k9vumvp3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT ukqdkr64bxreqdbn6b4k9vumvp3 UNIQUE (skill_name);


--
-- Name: applications unique_job_applicant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT unique_job_applicant UNIQUE (job_id, applicant_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- PostgreSQL database dump complete
--
