-- Add email verification support.
-- Existing accounts are marked verified to preserve their current login access.
ALTER TABLE users
    ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT TRUE;

-- Add original experience dates.
ALTER TABLE experiences
    ADD COLUMN original_start_date DATE;

ALTER TABLE experiences
    ADD COLUMN original_end_date DATE;

-- Store email verification and password-reset OTPs.
CREATE TABLE email_otps (
    otp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    otp VARCHAR(6) NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_email_otps_email ON email_otps(email);

-- Store recruiter and company profiles.
CREATE TABLE recruiter_profiles (
    recruiter_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    phone VARCHAR(20),
    designation VARCHAR(100),
    company_name VARCHAR(200) NOT NULL,
    company_email VARCHAR(255) NOT NULL,
    company_phone VARCHAR(20),
    company_website VARCHAR(500),
    industry VARCHAR(100),
    company_size VARCHAR(50),
    company_address TEXT,
    CONSTRAINT fk_recruiter_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Store additional applicant resume profile information.
CREATE TABLE resume_profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL UNIQUE,
    phone VARCHAR(50),
    linkedin TEXT,
    github TEXT,
    portfolio TEXT,
    projects JSONB,
    certifications JSONB,
    achievements JSONB,
    CONSTRAINT fk_resume_profiles_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(resume_id)
        ON DELETE CASCADE
);
