spring.application.name=resume-screening-backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/resume_screening_db
spring.datasource.username=postgres
spring.datasource.password=admin

#Password Reset Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=resumescreening.notification@gmail.com
spring.mail.password=eqrk nuyp ydmv svbj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# Server
server.port=8081

# AI Service
ai.service.url=http://localhost:8000

# Temporary security debugging
logging.level.org.springframework.security=DEBUG